swagger: '2.0'
info:
  title: Pet Api
  description: Cadastro de Pet's
  version: "1.0.0"
  
produces:
  - application/json

paths:
  /{petId}:
    get:
      summary: Pet informations
      description: returns informations about the pet
      parameters:
        - name: petId
          in: path
          type: number
          format: double
          description: Id do pet
          required: true
      responses:
        '200':
          description: Operation sucsessfull
          
    
  /newPet:
    post:
      summary: create a new pet
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: pet
          in: body
          description: add a new pet
          schema:
            $ref: '#/definitions/Pet'
          required: true
      responses:
        200:
          description: Create a new Pet
     
  /removePet/{petId}:
    post:
      summary: Delete a pet
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: petId
          in: path
          type: number
          format: double
          required: true
      responses:
        200:
          description: Delete a pet
          
definitions:
  Pet:
    type: object
    properties:
      name:
        type: string
  
